# Random - hw
## Libraries and functions

In [3]:
import numpy as np
import pandas as pd
import scipy.stats as ss
import matplotlib.pyplot as plt
import statsmodels.stats.api as sms
import seaborn as sns
from statsmodels.stats.proportion import proportion_confint
from tqdm import tqdm

In [56]:
def population_sample_parameter(dataset, column):
    '''функция определяет долю значений для выбранного параметра в полном наборе данных'''
    print(column)
    print(dataset[column].value_counts(normalize = True).to_string())
    print('-------------')
    print('Доля значений параметра в полном наборе данных:')

# Main tasks

## Первый кейс

В первом кейсе вам нужно самому подготовить выборку для возможного воздействия (например, рассылки пушей). Для этого вам в начале нужно сформировать стратифицированную выборку, а после проверить, репрезентативна ли она.

In [10]:
df_data1 = pd.read_csv('./data/5. homework_task_2.csv').dropna()

In [28]:
print(df_data1.shape)
df_data1.isna().sum()

(130112, 6)

passport_id            0
region                 0
platform               0
user_type_cars_name    0
number_ads             0
revenue                0
dtype: int64

In [13]:
df_data1.head()

,passport_id,region,platform,user_type_cars_name,number_ads,revenue
0,144161634,Санкт-Петербург,android,cars_seller,2,1080
1,132683716,Калининград,android,cars_simple,1,190
2,142653188,Санкт-Петербург,android,cars_seller,1,0
3,124199631,Казань,android,cars_simple,1,190
4,144045240,Казань,android,cars_simple,1,0

In [26]:
cols = ['region', 'platform', 'user_type_cars_name']

df_data1.groupby('platform').passport_id.count() / len(df_data1)

platform
android    0.641217
desktop    0.020844
ios        0.337179
mobile     0.000761
Name: passport_id, dtype: float64

In [34]:
df_data1.shape[0] * 0.05

6505.6

In [35]:
df_sample1 = df_data1.groupby('platform').sample(frac=0.05)

In [38]:
df_sample1.groupby('platform').passport_id.count() / len(df_sample1)

platform
android    0.641156
desktop    0.020901
ios        0.337175
mobile     0.000768
Name: passport_id, dtype: float64

In [39]:
df_sample1

,passport_id,region,platform,user_type_cars_name,number_ads,revenue
85086,144099952,Казань,android,cars_simple,1,1294
50843,137317103,Челябинск,android,cars_simple,1,0
96370,143437752,Новосибирск,android,cars_simple,1,0
47004,133564813,Казань,android,cars_simple,1,190
8225,123722119,Москва,android,cars_simple,1,0
...,...,...,...,...,...,...
68930,137816763,Москва,mobile,cars_simple,1,1645
86728,131596173,Воронеж,mobile,cars_seller,1,410
89937,131530503,Новосибирск,mobile,cars_simple,1,0
371,140661255,Екатеринбург,mobile,cars_simple,1,360
70784,123910034,Волгоград,mobile,cars_simple,1,380

## Второй кейс

In [42]:
df_data2 = pd.read_csv('./data/5. homework_task_3.csv')

In [45]:
df_data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26018 entries, 0 to 26017
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           26018 non-null  int64
 1   passport_id          26018 non-null  int64
 2   region               26018 non-null  object
 3   platform             26018 non-null  object
 4   user_type_cars_name  26018 non-null  object
 5   number_ads           26018 non-null  int64
 6   revenue              26018 non-null  int64
 7   vas                  26018 non-null  int64
 8   combined             26018 non-null  object
 9   combined_weight      26018 non-null  float64
 10  group                26018 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 2.2+ MB

In [44]:
df_data2.head()

,Unnamed: 0,passport_id,region,platform,user_type_cars_name,number_ads,revenue,vas,combined,combined_weight,group
0,105602,136957831,Волгоград,android,cars_seller,1,0,0,"('Волгоград', 'android', 'cars_seller', 0)",0.000007,['A']
1,46619,142530464,Волгоград,android,cars_seller,1,0,0,"('Волгоград', 'android', 'cars_seller', 0)",0.000007,['B']
2,97503,143220356,Волгоград,android,cars_seller,2,0,0,"('Волгоград', 'android', 'cars_seller', 0)",0.000007,['B']
3,35633,137497307,Волгоград,android,cars_seller,1,0,0,"('Волгоград', 'android', 'cars_seller', 0)",0.000007,['A']
4,52222,131622431,Волгоград,android,cars_seller,1,0,0,"('Волгоград', 'android', 'cars_seller', 0)",0.000007,['A']

In [47]:
cols = ['region', 'platform', 'user_type_cars_name', 'vas']
df_data2.groupby(cols).passport_id.count() / len(df_data1)

region     platform  user_type_cars_name  vas
Волгоград  android   cars_seller          0      0.000038
                                          1      0.000115
                     cars_simple          0      0.001068
                                          1      0.001061
           desktop   cars_seller          0      0.000008
                                                   ...
Челябинск  ios       cars_seller          0      0.000069
                                          1      0.000254
                     cars_simple          0      0.001299
                                          1      0.001230
           mobile    cars_simple          1      0.000008
Name: passport_id, Length: 306, dtype: float64

In [53]:
np.random.seed(1)
df_sample2 = df_data2.groupby(cols).sample(frac=0.2)

In [54]:
print(df_sample2.shape)

df_sample2.groupby(cols).passport_id.count() / len(df_sample2)

(5195, 11)

region     platform  user_type_cars_name  vas
Волгоград  android   cars_seller          0      0.000192
                                          1      0.000577
                     cars_simple          0      0.005390
                                          1      0.005390
           desktop   cars_simple          1      0.000192
                                                   ...
Челябинск  ios       cars_dealer          1      0.000192
                     cars_seller          0      0.000385
                                          1      0.001347
                     cars_simple          0      0.006545
                                          1      0.006160
Name: passport_id, Length: 216, dtype: float64

In [58]:
# population_sample_parameter(df_data2, cols)

In [59]:
print('Доля значений параметра в полном наборе данных:')
parameter_list = ['vas', 'platform']
for step in parameter_list:
    population_sample_parameter(df_data2, step)

Доля значений параметра в полном наборе данных:
vas
vas
1    0.522638
0    0.477362
-------------
Доля значений параметра в полном наборе данных:
platform
platform
android    0.641287
ios        0.337267
desktop    0.020793
mobile     0.000653
-------------
Доля значений параметра в полном наборе данных:

In [80]:
# сформируем выборку из 10 тыс. пользователей, исходя из условия,
# что параметры представлены в соотношении, как для полного набора данных
def get_strat(df, cols, n=10000):
    # df['combined'] = list(zip(df['vas'], df['platform']))
    df['combined'] = df.loc[:, cols].apply(lambda row: tuple(row[c] for c in cols), axis=1)

    #формируем столбец с комбинацией целевых параметров
    
    weight = df['combined'].value_counts(normalize=True)
    counts = df['combined'].value_counts()
    
    df['combined_weight'] = df['combined'].apply(lambda x: weight[x]/counts[x]) # рассчитываем вес каждой комбинации, по которому будет сэмплироваться выборка
    strat_sample_dataset = df.sample(n, weights=df['combined_weight']) # сэмплируем по весам комбинации параметров
    return strat_sample_dataset

get_strat(df_data2, parameter_list)

,Unnamed: 0,passport_id,region,platform,user_type_cars_name,number_ads,revenue,vas,combined,combined_weight,group
8754,82243,123511544,Москва,desktop,cars_simple,1,1180,1,"(1, desktop)",0.000038,['A']
13937,80092,142550536,Новосибирск,android,cars_simple,1,0,0,"(0, android)",0.000038,['B']
8278,12763,134649927,Москва,android,cars_simple,1,540,1,"(1, android)",0.000038,['B']
23270,2629,141083797,Сочи,android,cars_simple,1,190,1,"(1, android)",0.000038,['B']
23308,38707,130803595,Сочи,android,cars_simple,1,250,1,"(1, android)",0.000038,['B']
...,...,...,...,...,...,...,...,...,...,...,...
17055,115038,138165503,Ростов-на-Дону,android,cars_simple,1,550,1,"(1, android)",0.000038,['B']
1632,88467,124823577,Екатеринбург,android,cars_simple,1,190,1,"(1, android)",0.000038,['B']
6912,35616,134355831,Москва,android,cars_simple,1,0,0,"(0, android)",0.000038,['B']
12840,61287,136296657,Новосибирск,android,cars_simple,2,0,0,"(0, android)",0.000038,['A']
11205,14637,141751279,Москва,ios,cars_simple,1,490,1,"(1, ios)",0.000038,['B']

In [81]:
# выведем долю значений для каждого параметра в выборке
print('Доля значений параметра в выборке из 10 тыс. пользователей:')
for step in parameter_list:
    population_sample_parameter(
        get_strat(df_data2, parameter_list), step
    )

Доля значений параметра в выборке из 10 тыс. пользователей:
vas
vas
1    0.5281
0    0.4719
-------------
Доля значений параметра в полном наборе данных:
platform
platform
android    0.6371
ios        0.3387
desktop    0.0233
mobile     0.0009
-------------
Доля значений параметра в полном наборе данных: