# Библиотеки

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import pingouin as pg
import seaborn as sns

## 10.8 Ложные (частные\получастные) корреляции

In [11]:
d = pd.read_spss('./data/SPSS22.sav')

In [15]:
pg.rcorr(d)

          Возраст  Семья Дна1члена
Возраст         -    ***       ***
Семья       0.659      -       ***
Дна1члена   0.883  0.611         -

In [16]:
pg.pairwise_corr(data=d, method='spearman')

,X,Y,method,alternative,n,r,CI95%,p-unc,power
0,Возраст,Семья,spearman,two-sided,89,0.669359,"[0.54, 0.77]",7.454062e-13,1.000000
1,Возраст,Дна1члена,spearman,two-sided,89,0.864000,"[0.8, 0.91]",1.164397e-27,1.000000
2,Семья,Дна1члена,spearman,two-sided,89,0.616988,"[0.47, 0.73]",1.206470e-10,0.999999

In [17]:
pg.pairwise_corr(data=d, method='spearman', covar='Возраст')

,X,Y,method,covar,alternative,n,r,CI95%,p-unc
0,Семья,Дна1члена,spearman,['Возраст'],two-sided,89,0.103357,"[-0.11, 0.31]",0.33792

In [19]:
pg.partial_corr(data=d, x='Семья', y='Дна1члена', method='spearman', covar='Возраст')

           n         r          CI95%    p-val
spearman  89  0.103357  [-0.11, 0.31]  0.33792