# Библиотеки

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import pingouin as pg
import seaborn as sns

## 9.11 Тест 2-х групп (почти самостоятельное задание)

In [2]:
df = pg.read_dataset('anova')

In [3]:
df.sample(n=5, random_state=42)

    Subject      Hair color  Pain threshold
0         1     Light Blond              62
5         6      Dark Blond              63
11       12  Light Brunette              50
1         2     Light Blond              60
8         9      Dark Blond              41

In [4]:
df.groupby('Hair color')['Subject'].count()

Hair color
Dark Blond        5
Dark Brunette     5
Light Blond       5
Light Brunette    4
Name: Subject, dtype: int64

In [5]:
equal_var = pg.homoscedasticity(data=df, dv='Pain threshold', group='Hair color').at['levene', 'equal_var']

pg.homoscedasticity(data=df, dv='Pain threshold', group='Hair color')

               W      pval  equal_var
levene  0.392743  0.760016       True

In [6]:
if equal_var:
    print('anova')
    res = pg.anova(data=df, dv='Pain threshold', between='Hair color')
else:
    print('welch_anova')
    res = pg.welch_anova(data=df, dv='Pain threshold', between='Hair color')

res

anova

       Source  ddof1  ddof2         F     p-unc       np2
0  Hair color      3     15  6.791407  0.004114  0.575962

In [7]:
if equal_var:
    print('anova')
    res = pg.pairwise_tukey(data=df, dv='Pain threshold', between='Hair color')
else:
    print('welch_anova')
    res = pg.pairwise_gameshowell(data=df, dv='Pain threshold', between='Hair color')

res

anova

,A,B,mean(A),mean(B),diff,se,T,p-tukey,hedges
0,Dark Blond,Dark Brunette,51.2,37.4,13.8,5.168623,2.669957,0.074068,1.413596
1,Dark Blond,Light Blond,51.2,59.2,-8.0,5.168623,-1.547801,0.435577,-0.810661
2,Dark Blond,Light Brunette,51.2,42.5,8.7,5.482153,1.586968,0.414728,0.982361
3,Dark Brunette,Light Blond,37.4,59.2,-21.8,5.168623,-4.217758,0.003708,-2.336811
4,Dark Brunette,Light Brunette,37.4,42.5,-5.1,5.482153,-0.930291,0.789321,-0.626769
5,Light Blond,Light Brunette,59.2,42.5,16.7,5.482153,3.046249,0.036647,2.015280

## 9.13 Сравнение незав. групп:более 2-х групп,непараметрика, с пост-хок

In [8]:
pg.kruskal(data=df, dv='Pain threshold', between='Hair color')

             Source  ddof1         H     p-unc
Kruskal  Hair color      3  10.58863  0.014172

In [9]:
pg.pairwise_tests(data=df, dv='Pain threshold', between='Hair color', parametric=False, padjust="bonf")

,Contrast,A,B,Paired,Parametric,U-val,alternative,p-unc,p-corr,p-adjust,hedges
0,Hair color,Dark Blond,Dark Brunette,False,False,23.0,two-sided,0.031746,0.190476,bonf,1.413596
1,Hair color,Dark Blond,Light Blond,False,False,7.0,two-sided,0.309524,1.000000,bonf,-0.810661
2,Hair color,Dark Blond,Light Brunette,False,False,16.5,two-sided,0.139983,0.839895,bonf,0.982361
3,Hair color,Dark Brunette,Light Blond,False,False,1.0,two-sided,0.015873,0.095238,bonf,-2.336811
4,Hair color,Dark Brunette,Light Brunette,False,False,5.0,two-sided,0.285714,1.000000,bonf,-0.626769
5,Hair color,Light Blond,Light Brunette,False,False,19.0,two-sided,0.031746,0.190476,bonf,2.015280

In [10]:
pg.mwu(x=(df.loc[df['Hair color'] == 'Dark Blond', 'Pain threshold']), y=(df.loc[df['Hair color'] == 'Dark Brunette', 'Pain threshold']))

     U-val alternative     p-val   RBC  CLES
MWU   23.0   two-sided  0.031746  0.84  0.92

In [11]:
pg.multicomp([0.031746,0.309524,0.139983,0.015873,0.285714,0.031746], method='bonf')

(array([False, False, False, False, False, False]),
 array([0.190476, 1.      , 0.839898, 0.095238, 1.      , 0.190476]))