# Библиотеки

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import pingouin as pg
import seaborn as sns

## 10.7 Корреляция для повторных замеров

- Subject номер пациента/испытуемого (у каждого человека было несколько замеров -  и важно что у каждого было РАЗНОЕ количество замеров: например, у 1 пациента было 4 замера, а у 7 только 3 замера, а у 8 было 8 замеров....)
- pH измеренное значение кислотности крови (pH)
- PaCO2 измеренное у того же пациента в тот же момент парциальное давление углекислого газа в крови в кПа

In [2]:
df = pg.read_dataset('rm_corr')

In [5]:
df.head(3)

   Subject    pH  PacO2
0        1  6.68   3.97
1        1  6.53   4.12
2        1  6.43   4.09

In [6]:
pg.rm_corr(data=df, x='pH', y='PacO2', subject='Subject')

               r  dof      pval           CI95%     power
rm_corr -0.50677   38  0.000847  [-0.71, -0.23]  0.929579

In [7]:
PH_LOW, PH_HIGH = 7.35, 7.45
PCO2_LOW, PCO2_HIGH = 4.7, 6.0

df['Диагноз']='Неоднозначно: метаболический или смешанный'

df.loc[(df['pH'] < PH_LOW) & (df['PacO2'] > PCO2_HIGH), 'Диагноз'] = 'Ацидоз'
df.loc[(df['pH'] > PH_HIGH) & (df["PacO2"] < PCO2_LOW), "Диагноз"] = 'Алкалоз'
df.loc[(df['pH'].between(PH_LOW, PH_HIGH)) & (df['PacO2'].between(PCO2_LOW, PCO2_HIGH)), 'Диагноз'] = 'Норма'

In [9]:
df['Диагноз'].value_counts()

Диагноз
Неоднозначно: метаболический или смешанный    37
Норма                                          6
Ацидоз                                         4
Name: count, dtype: int64